alias ug      'ugrep --color --pager'
alias ux      'ugrep --color --pager -UX'
alias uz      'ugrep --color --pager -z'
alias grep    'ugrep --color --pager -G'
alias egrep   'ugrep --color --pager -E'
alias fgrep   'ugrep --color --pager -F'
alias xgrep   'ugrep --color --pager -W'
alias zgrep   'ugrep --color --pager -zG'
alias zegrep  'ugrep --color --pager -zE'
alias zfgrep  'ugrep --color --pager -zF'
alias xdump   'ugrep --color --pager -X'
